services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: appdb
      TZ: Asia/Seoul
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -h localhost -p${DB_PASS} -h localhost || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:mysql://mysql:3306/appdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      DB_USER: root
      DB_PASS: ${DB_PASS}
    ports:
      - "8080:8080"

volumes:
  dbdata:
