spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  flyway:
    enabled: true
    clean-disabled: false

jwt:
  secret: bqRgdYiJ8PphtR0lZhoo8Rzch+TJechjMOyF9+j8pSQ=

security:
  otp:
    pepper: dev-otp-pepper-change-in-production
  refresh:
    pepper: dev-refresh-pepper-change-in-production

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,env,configprops
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.example.final_projects: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      aiService:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
