spring:
  datasource:
    url: jdbc:mysql://localhost:3307/appdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rootpw
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update     # 개발 중에는 update, 운영에서는 validate 권장
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul

  jackson:
    time-zone: Asia/Seoul

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8080

  management:
    endpoints:
      web:
        exposure:
          include: health,mappings
    endpoint:
      health:
        show-details: always

rest:
  ai:
    base-url: http://3.36.109.88:8000

security:
  otp:
    pepper: ${OTP_PEPPER}         # 환경변수/Secrets Manager로 주입 (필수)
    code-length: 6
    ttl-seconds: 300              # OTP 유효기간 5분
    token-ttl-seconds: 600        # pre-signup 검증토큰 유효기간 10분
    resend-min-seconds: 60        # 재발송 쿨다운(초)
    max-resend-per-hour: 5
    max-attempts: 5



logging:
  charset:
    console: UTF-8
    file: UTF-8



