jwt:
  secret: bqRgdYiJ8PphtR0lZhoo8Rzch+TJechjMOyF9+j8pSQ=

resilience4j:
  circuitbreaker:
    instances:
      aiService:
        slidingWindowSize: 3
        minimumNumberOfCalls: 1
        failureRateThreshold: 50
        waitDurationInOpenState: 1s
        permittedNumberOfCallsInHalfOpenState: 1

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    enabled: false
