spring:
  datasource:
    url: jdbc:mysql://localhost:3307/appdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rootpw
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/seed

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.flywaydb: DEBUG


        #개발환경용 키라서 임시 값이 배포환경에 넣을때는 환경변수 주입 방식 사용해야함 secret도 다시 생성해야함
jwt:
  secret: bqRgdYiJ8PphtR0lZhoo8Rzch+TJechjMOyF9+j8pSQ=
  access-validaity-ms: 1800000  #30min
  refresh-validity-ms: 1209600000 #14day
