spring:
  datasource:
    url: jdbc:mysql://localhost:3307/appdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rootpw
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update     # 개발 중에는 update, 운영에서는 validate 권장
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul

  jackson:
    time-zone: Asia/Seoul

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8080

  management:
    endpoints:
      web:
        exposure:
          include: health,mappings
    endpoint:
      health:
        show-details: always


